spring.application.name=expense-app

# .NET Karşılığı: Server=localhost,1433; Database=expenseDb; User=sa; Password=...
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ExpenseDb;encrypt=true;trustServerCertificate=true

# Kimlik Bilgileri
spring.datasource.username=sa
spring.datasource.password=admin123456789

# Sürücü Sınıfı (NuGet paketi karşılığı)
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# EF Core 'Update-Database' Karşılığı
# update: Tablolar yoksa oluşturur, varsa günceller.
spring.jpa.hibernate.ddl-auto=update

# Konsolda SQL sorgularını ve parametrelerini temizce görelim
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.issuer=qoex.expenseapp
jwt.audience=qoex.client
# Örnek 256-bit Key (Base64):
jwt.security-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.access-token-expiration=60
jwt.refresh-token-expiration=7

